stages:
  - build
  - deploy

variables:
  GO_VERSION: "1.20"

build:
  stage: build
  image: golang:1.20-bullseye
  before_script:
    - apt-get update && apt-get install -y gcc-aarch64-linux-gnu
  script:
    - go version
    - cd service
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o ../websf
  artifacts:
    paths:
      - websf

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no websf $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
  only:
    - hey