name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set working directory and install dependencies
      run: |
        cd web
        npm install

    - name: Build project
      run: |
        cd web
        npm run build

    - name: Compress dist folder
      run: |
        cd web
        tar -czf ../websf.tar.gz -C dist .

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "websf.tar.gz"
        target: "/tmp/"
        overwrite: true

    - name: Extract files on server and move to nginx directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo rm -rf /usr/share/nginx/html/websf
          sudo mkdir -p /usr/share/nginx/html/websf
          sudo tar -xzf /tmp/websf.tar.gz -C /usr/share/nginx/html/websf
          sudo rm /tmp/websf.tar.gz
          sudo chown -R nginx:nginx /usr/share/nginx/html/websf
          sudo chmod -R 755 /usr/share/nginx/html/websf